Implement Backend Error Redesign
String-xyz/go-lib pull request #7
Opened 2023-03-02 00:33 UTC by alcalawil

2023-03-06 18:52 UTC, saito-sv approved these changes
LGTM

2023-03-06 18:52 UTC, saito-sv commented on httperror/http_error.go
> +		return c.JSON(http.StatusInternalServerError, JSONError{Message: strings.Join(message, " "), Code: "INTERNAL_SERVER"})
Nit: Optional. 
```suggestion
		return c.JSON(http.StatusInternalServerError, JSONError{Message: strings.Join(message, " "), Code: "INTERNAL})
```

2023-03-07 19:47 UTC, ocasta181 requested changes

2023-03-07 19:47 UTC, ocasta181 commented on database/redis.go
> +	serrors "github.com/String-xyz/go-lib/stringerror"
```suggestion
	serror "github.com/String-xyz/go-lib/stringerror"
```

2023-03-07 19:47 UTC, ocasta181 commented on database/redis.go
> +			return nil, common.StringError(serrors.NOT_FOUND)
```suggestion
			return nil, common.StringError(serror.NOT_FOUND)
```

2023-03-07 19:47 UTC, ocasta181 commented on database/redis.go
> +			return nil, common.StringError(serrors.NOT_FOUND)
```suggestion
			return nil, common.StringError(serror.NOT_FOUND)
```

2023-03-07 19:47 UTC, ocasta181 commented on repository/repository.go
> +	serrors "github.com/String-xyz/go-lib/stringerror"
```suggestion
	serror "github.com/String-xyz/go-lib/stringerror"
```

2023-03-07 19:47 UTC, ocasta181 commented on repository/repository.go
> +		return m, serrors.NOT_FOUND
```suggestion
		return m, serror.NOT_FOUND
```

2023-03-07 19:47 UTC, ocasta181 commented on repository/repository.go
> +		return m, serrors.NOT_FOUND
```suggestion
		return m, serror.NOT_FOUND
```

2023-03-07 19:49 UTC, alcalawil commented on httperror/http_error.go
> +		return c.JSON(http.StatusInternalServerError, JSONError{Message: strings.Join(message, " "), Code: "INTERNAL_SERVER"})
later reftactor

2023-03-07 20:01 UTC, ocasta181 approved these changes

2023-03-07 20:02 UTC, merged